version: '3.1'

volumes:
  pg_banking_system:

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=banking_system_db
    volumes:
      - pg_banking_system:/var/lib/postgresql/data
    ports:
      - 8912:5432
